name: "godot-ci export"
on: 
  push:
    branches: ["release"]
  workflow_dispatch:
    workflows: [export-web]

env:
  GODOT_VERSION: 4.7
  EXPORT_NAME: gmtk-jam-2026

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: godot -v --export "HTML5" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./build/web/
